server:
  port: 8081

spring:
  application:
    name: demo-user
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/example?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    druid:
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: syf
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
      filter:
        wall:
          enabled: true
        stat:
          enabled: true
        slf4j:
          enabled: true
#seata 配置
seata:
  application-id: seata-server
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: nacos
    nacos:
      group: SEATA_GROUP
      application: seata-server
      server-addr: ${spring.cloud.nacos.discovery.server-addr}


# nacos 配置
  cloud:
    alibaba:
      seata:
        # http://seata.io/zh-cn/docs/user/txgroup/transaction-group.html
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
